### ISSUE TITLE
1.0.4 version problem with influx 0.9x

### ISSUE THREAD

**Issue by discoduck2x** [poxet/Influx-Capacitor#5]
Data do gets sent to influx 0.9v but:
the tags have "" around them making them not usable?
"show tag keys from Processor" returns nothing, also the time column is not epoch meaning its corrupt?
tried with grafana and cant graph anything :/

**Comment by poxet** [comment]
Did not test this enouht it seems. Ill fix shortly.

**Comment by poxet** [comment]
So, the issue with "" should be fixed now, and the time should be utc.
I put the machineName as a tag.

I still have some testing and developing left to do and I do not think that version 0.8x currently works as it should.

I will create a new chocolatey package when all is done, or if someone want to use that for testing.

**Comment by discoduck2x** [comment]
if i were you i would stop supporting influx 0.8 :)

**Comment by poxet** [comment]
I just pushed version 1.0.5.0. With this version I got my counters to work witn influxDB ver 0.9.2.1.

I will leave the issue open until someone else also thinks that it works.

**Comment by discoduck2x** [comment]
where is the url saved for server & database? I want to change db details but cant find it in any conf file nor in registry?
(uninstall does not remove all that it should apparently?)

**Comment by poxet** [comment]
The settings file is for now stored in the ProgramData-folder. Propably here "C:\ProgramData\Thargelion\InfluxDB.Net.Collector"

You can also change setting by running the console version of the application "InfluxDB.Net.Collector.Console.exe" and type setup change "setup change".

I will write about this in README.md and also make sure that it is removed when uninstalling.

**Comment by discoduck2x** [comment]
im still unable to draw graphs with grafana, if i do "show measurements" and drill down via the influx cli it doesnt look right.

you should write series name ,value tags like: 
processor,hostname=server01,cpu=_Total value=75 1435362189575692182

(last bit is time in epoch- if omitted it takes time of write in db)

**Comment by poxet** [comment]
Perhaps your suggestion is better. I will have a look at that.

As of now this query in graphana should work.
SELECT mean("_Total") FROM "Processor" WHERE $timeFilter GROUP BY time($interval)

Is uppose you want it to be something like this...
SELECT mean(value) FROM "Processor" WHERE "MachineName" = '"GAMMA"' AND "cpu"="_Total" AND $timeFilter GROUP BY time($interval)
right?

Also, when running Grafana version 2.0.2 I can agree that it looks really bad. When using Grafana 2.1.0-pre1 it looks much better and you can actually click your way to get the values, even now.

**Comment by discoduck2x** [comment]
something like that yes- try using templating variables in grafana 2.1 and you´ll see you cant find any tags to play with, i cant give u more detailed examples if u want to

**Comment by poxet** [comment]
Have you been able to get any graphs out at all with version 1.0.5?

Please send examples and Ill try to make it happen. :)

Can we get in contact to talk about this directly? (Email, slack or something like that)

**Comment by poxet** [comment]
A major update with version 1.0.6 should solve the problem.

Also the project is renamed to Influx-Capacitor.
